// WordPress webpack config.
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

// Plugins.
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );

// Utilities.
const path = require( 'path' );

// Add any a new entry point by extending the webpack config.
module.exports = {
	...defaultConfig,
	...{
		entry: {
			...defaultConfig.entry(),
			'supports/filter': path.resolve(
				process.cwd(),
				'src/supports',
				'filter.js'
			),
			'components/index': path.resolve(
				process.cwd(),
				'src/components',
				'index.js'
			),
			'controls/index': path.resolve(
				process.cwd(),
				'src/controls',
				'index.js'
			),
			'store-controls/index': path.resolve(
				process.cwd(),
				'src/store-controls',
				'index.js'
			)
		},
		plugins: [
			// Include WP's plugin config.
			...defaultConfig.plugins,

			// Removes the empty `.js` files generated by webpack but
			// sets it after WP has generated its `*.asset.php` file.
			new RemoveEmptyScriptsPlugin( {
				stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
			} ),
		],
	},
};
